export default {
    products:[
        {
        _id:'1',
        name:'Slim Brown Suite',
        category:'Shirts',
        image:'/images/d13.png',
        price:1240,
        brand:'Armani',
        rating:4.5,
        numReviews:10,
        countInStock:6,
    },
    {
        _id:'2',
        name:'Tailored Fit Grey Suit',
        category:'Shirts',
        image:'/images/d3.jpg',
        price:1350,
        brand:'Z-Suit',
        rating:4.9,
        numReviews:180,
        countInStock:0,
    },

    {
        _id:'3',
        name:'Regular Grey Suit',
        category:'Suite',
        image:'/images/d8.jpg',
        price:1300,
        brand:'Tom Ford',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
    {
        _id:'4',
        name:'Special Z Suite',
        category:'Shirts',
        image:'/images/d9.jpeg',
        price:1550,
        brand:'Z-Suite',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
    {
        _id:'5',
        name:'Black pants',
        category:'Shirts',
        image:'/images/d14.png',
        price:150,
        brand:'Givenchy',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
    {
        _id:'6',
        name:'Pants with Stripes',
        category:'Shirts',
        image:'/images/d15.jpg',
        price:250,
        brand:'Tom Ford',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
    {
        _id:'7',
        name:'Khaki pants',
        category:'Shirts',
        image:'/images/d16.png',
        price:170,
        brand:'Gucci',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
    {
        _id:'8',
        name:'Blue Pants',
        category:'Shoes',
        image:'/images/d17.jpg',
        price:1180,
        brand:'Giorgio Armani',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
    {
        _id:'9',
        name:'Z-Shoes',
        category:'Shoes',
        image:'/images/d18.jpg',
        price:1550,
        brand:'Z-Suit',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
    {
        _id:'10',
        name:'Black Lether',
        category:'Shoes',
        image:'/images/d19.jpg',
        price:570,
        brand:'Giorgio Armani',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
    {
        _id:'11',
        name:'Dark Brown Armani',
        category:'Shoes',
        image:'/images/d20.png',
        price:450,
        brand:'Giorgio Armani',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
    {
        _id:'12',
        name:'Brown Oxford',
        category:'Shoes',
        image:'/images/d21.png',
        price:750,
        brand:'Tom Ford',
        rating:4.5,
        numReviews:11,
        countInStock:4,
    },
]
}